# Generated by Django 5.2.3 on 2025-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
