# Generated by Django 5.2.3 on 2025-07-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='canvas_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
