"""
Django settings for chat_projekt project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Tajný klíč
SECRET_KEY = os.environ.get('SECRET_KEY') # Získá tajný klíč 

# Debug mode je vypnutý v produkci (DEBUG = False)
DEBUG = False

# Allowed hosts - zde přidáme hostitele, na kterých může běžet aplikace
ALLOWED_HOSTS = ['neustadt-chat.onrender.com', '127.0.0.1']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# ASGI nastavení je důležité pro WebSocket a další asynchronní funkce
ASGI_ALLOWED_HOSTS = [
    'neustadt-chat.onrender.com',
]

# Application definition

INSTALLED_APPS = [
    'daphne',       # Správný název, musí být první
    'channels',     # Správný název, jako samostatná položka

    # Tvoji aplikaci je lepší uvádět jednoduše jako 'chat'
    'chat',

    # Zbytek Django aplikací
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Pro statické soubory
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chat_projekt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat_projekt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Používáme dj_database_url pro snadnou konfiguraci databáze
DATABASES = {
    'default': dj_database_url.config(
        # Render nám dodá URL k databázi v proměnné DATABASE_URL
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600 # Maximální doba udržení připojení v sekundách
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Přidej na konec souboru
ASGI_APPLICATION = 'chat_projekt.asgi.application'

# Channel layers umožňují komunikaci mezi různými částmi aplikace
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer", # Správný backend pro Redis
        "CONFIG": {
            # Render nám dodá URL k Redis v proměnné REDIS_URL
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')], # Výchozí adresa Redis serveru 
        },
    },
}

# Cesty pro přihlášení a odhlášení
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chat-page'
LOGOUT_REDIRECT_URL = 'login'
# Statické soubory pro WhiteNoise
STATIC_ROOT = BASE_DIR / 'staticfiles'

